backend:
    name: git-gateway
    branch: master # Branch to update (optional; defaults to master)
    commit_messages:
        create: "Create {{collection}} '{{slug}}'"
        update: "Update {{collection}} '{{slug}}'"
        delete: "Delete {{collection}} '{{slug}}'"
        uploadMedia: "Upload '{{path}}'"
        deleteMedia: "Delete '{{path}}'"

media_folder: "src/assets/images" # Location where files will be stored in the repo
public_folder: "src/assets/images" # The src attribute for uploaded media
site_url: "https://0nisec.blog"
display_url: "https://0nisec.blog"

collections:
    - name: "writeups" # Used in routes, e.g., /admin/collections/blog
      label: "Writeups" # Used in the UI
      folder: "src/content/writeup" # The path to the folder where the documents are stored
      create: true # Allow users to create new documents in this collection
      fields: # The fields for each document, usually in frontmatter
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Topics", name: "topics", widget: "list" }
          - { label: "Description", name: "description", widget: "text" }
          - {
                label: "Publish Date",
                name: "date",
                date_format: "MM/DD/YYYY",
                widget: "datetime",
            }
          - {
                label: "Updated Date",
                name: "updatedDate",
                date_format: "MM/DD/YYYY",
                widget: "datetime",
            }
          - { label: "Hero Image", name: "heroImage", widget: "image" }
          - {
                label: "Difficulty",
                name: "difficulty",
                widget: "select",
                options: ["Easy", "Medium", "Hard", "Insane"],
            }
          - {
                label: "OS",
                name: "os",
                widget: "select",
                options: ["Windows", "Linux"],
            }
          - { label: "Active", name: "active", widget: "boolean" }
          - { label: "Body", name: "body", widget: "markdown" }
